name: Build APK with EAS

on:
  workflow_dispatch:     # Allows manual trigger from GitHub
  push:
    branches:
      - main             # Runs when you push to main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧱 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 🛠 Install EAS CLI
        run: npm install -g eas-cli

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build APK with EAS
        run: eas build -p android --profile preview --non-interactive --no-wait
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
